/*
 * This file is part of the Combatant Client distribution.
 * Copyright (c) 2026 pivosos2007.
 *
 * Licensed under the GNU General Public License v3.0.
 */

package combatant.client.render.engine.deferred;

import combatant.client.render.engine.core.RenderPhase;

/** Stable world-frame insertion points. Ordering is part of the renderer contract. */
public enum DeferredStage {
    FRAME_SETUP(RenderPhase.WORLD_BEFORE_ENTITIES),
    SHADOW_PREPARE(RenderPhase.WORLD_BEFORE_ENTITIES),
    SHADOW_MAP(RenderPhase.WORLD_BEFORE_ENTITIES),
    SHADOW_FILTER(RenderPhase.WORLD_BEFORE_ENTITIES),
    PRE_GEOMETRY_COMPUTE(RenderPhase.WORLD_BEFORE_ENTITIES),
    OPAQUE_GEOMETRY(RenderPhase.WORLD_BEFORE_ENTITIES),
    CUTOUT_GEOMETRY(RenderPhase.WORLD_BEFORE_ENTITIES),
    HEIGHT_SURFACE(RenderPhase.WORLD_BEFORE_ENTITIES),
    POST_GEOMETRY_COMPUTE(RenderPhase.WORLD_BEFORE_ENTITIES),
    DEPTH_RESOLVE(RenderPhase.WORLD_BEFORE_ENTITIES),
    VELOCITY_RESOLVE(RenderPhase.WORLD_BEFORE_ENTITIES),
    DEPTH_PYRAMID(RenderPhase.WORLD_BEFORE_ENTITIES),
    SHADOW_CASCADE_RESOLVE(RenderPhase.WORLD_BEFORE_ENTITIES),
    CONTACT_SHADOW(RenderPhase.WORLD_BEFORE_ENTITIES),
    SHADOW_RESOLVE(RenderPhase.WORLD_BEFORE_ENTITIES),
    AMBIENT_OCCLUSION(RenderPhase.WORLD_BEFORE_ENTITIES),
    PRE_LIGHTING(RenderPhase.WORLD_BEFORE_ENTITIES),
    LIGHTING(RenderPhase.WORLD_BEFORE_ENTITIES),
    POST_LIGHTING(RenderPhase.WORLD_BEFORE_ENTITIES),
    FORWARD_OPAQUE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    PRE_TRANSLUCENCY_DEPTH_RESOLVE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    PRE_TRANSLUCENCY_VELOCITY_RESOLVE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    PRE_TRANSLUCENCY_DEPTH_PYRAMID(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    PRE_TRANSLUCENCY_TEMPORAL_VALIDATION(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    RADIANCE_CAPTURE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    INDIRECT_PREPARE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    INDIRECT_TRACE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    INDIRECT_TEMPORAL(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    INDIRECT_HISTORY(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    INDIRECT_COMPOSITE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_CAPTURE_PREPARE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_CAPTURE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_PREPARE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_TRACE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_RESOLVE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_TEMPORAL(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_DENOISE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_HISTORY(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    REFLECTION_COMPOSITE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    SKY_COMPOSITE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    WATER_MEDIUM_BOUNDARY(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    VOLUMETRIC_MEDIA_INJECT(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    VOLUMETRIC_MEDIA_INTEGRATE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    VOLUMETRIC_MEDIA_COMPOSITE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    WATER_REFLECTION_TRACE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    WATER_REFLECTION_TEMPORAL(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    WATER_REFLECTION_DENOISE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    WATER_REFLECTION_HISTORY(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    WATER_REFLECTION_RESOLVE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    WATER_SURFACE(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    PRE_TRANSLUCENCY(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    TRANSLUCENCY(RenderPhase.WORLD_BEFORE_TRANSLUCENT),
    POST_TRANSLUCENCY(RenderPhase.WORLD_AFTER_TRANSLUCENT),
    TEMPORAL_RESOLVE(RenderPhase.WORLD_AFTER_TRANSLUCENT),
    PRE_POST_PROCESS(RenderPhase.WORLD_POST_PRE_HAND),
    POST_PROCESS(RenderPhase.WORLD_POST_PRE_HAND),
    FINAL_COMPOSITE(RenderPhase.WORLD_POST_HAND);

    private final RenderPhase renderPhase;

    DeferredStage(RenderPhase renderPhase) {
        this.renderPhase = renderPhase;
    }

    public RenderPhase renderPhase() {
        return renderPhase;
    }
}
