# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=0.1.1
maven_group=pivosos2007
archives_base_name=combatant
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.152.2+26.2
sodium_version=mc26.2-0.9.1-fabric
iris_version=1.11.1+26.2-fabric
immediatelyfast_version=1.16.0+26.2-fabric
xaero_minimap_version=fabric-26.2-26.1.3
xaero_worldmap_version=fabric-26.2-1.41.1
viafabricplus_version=4.6.0
entityculling_version=1.10.5
