#version 430 core

/*
 * This file is part of the Combatant Client distribution.
 * Copyright (c) 2026 pivosos2007.
 *
 * Licensed under the GNU General Public License v3.0.
 */

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(binding = 0, rgba16f) readonly uniform image2D u_Source;
layout(binding = 1, rgba16f) writeonly uniform image2D u_Destination;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(u_Destination);
    if (any(greaterThanEqual(pixel, size))) return;
    imageStore(u_Destination, pixel, imageLoad(u_Source, pixel));
}
