#version 430 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;
layout(binding = 0) uniform sampler3D u_Source;
layout(binding = 1, r32f) writeonly uniform image3D u_Target;

void main() {
    ivec3 target = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 targetSize = imageSize(u_Target);
    if (any(greaterThanEqual(target, targetSize))) return;

    ivec3 sourceSize = textureSize(u_Source, 0);
    ivec3 base = target * 2;
    float maximum = 0.0;
    for (int z = 0; z < 2; ++z) {
        for (int y = 0; y < 2; ++y) {
            for (int x = 0; x < 2; ++x) {
                ivec3 p = min(base + ivec3(x, y, z), sourceSize - ivec3(1));
                maximum = max(maximum, texelFetch(u_Source, p, 0).r);
            }
        }
    }
    imageStore(u_Target, target, vec4(maximum, 0.0, 0.0, 0.0));
}
