#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(binding = 0) uniform sampler2D u_Radiance;
layout(binding = 1) uniform sampler2D u_Depth;
layout(binding = 2) uniform sampler2D u_Confidence;
layout(binding = 3) uniform sampler2D u_ReprojectionData;
layout(binding = 4, rgba16f) writeonly uniform image2D u_HistoryRadiance;
layout(binding = 5, r32f) writeonly uniform image2D u_HistoryDepth;
layout(binding = 6, r8) writeonly uniform image2D u_HistoryConfidence;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(u_HistoryRadiance);
    if (any(greaterThanEqual(pixel, size))) return;
    vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
    float entryDepth = textureLod(u_Depth, uv, 0.0).r;
    float reprojectionDepth = textureLod(u_ReprojectionData, uv, 0.0).z;
    if (entryDepth < 0.0) reprojectionDepth = -1.0;
    imageStore(u_HistoryRadiance, pixel, textureLod(u_Radiance, uv, 0.0));
    imageStore(u_HistoryDepth, pixel, vec4(reprojectionDepth, 0.0, 0.0, 0.0));
    imageStore(u_HistoryConfidence, pixel, vec4(textureLod(u_Confidence, uv, 0.0).r, 0.0, 0.0, 0.0));
}
