#version 430 core
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(binding = 0) uniform sampler2D u_Color;
layout(binding = 1, rgba16f) writeonly uniform image2D u_Output;
layout(binding = 2, r32f) writeonly uniform image2D u_Coc;
void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(u_Output);
    if (any(greaterThanEqual(p, size))) return;
    vec2 uv = (vec2(p) + 0.5) / vec2(size);
    imageStore(u_Output, p, textureLod(u_Color, uv, 0.0));
    imageStore(u_Coc, p, vec4(0.0));
}
